FROM node:16

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Add these lines to fix permissions
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

EXPOSE 3000

CMD ["npm", "start"]
